### ISSUE TITLE
ERROR 1125 (HY000) at line 29: Function 'lib_mysqludf_sys_info' already exists

### ISSUE THREAD

**Issue by vivekgkp** [mysqludf/lib_mysqludf_sys#26]
lib_mysqludf_sys]# ./install.sh
Compiling the MySQL UDF
gcc -m64 -fPIC -Wall -I/usr/local/mysql/include -I. -shared lib_mysqludf_sys.c -o /usr/lib64/mysql/plugin/lib_mysqludf_sys.so
MySQL UDF compiled successfully

Please provide your MySQL root password
Enter password:
ERROR 1125 (HY000) at line 29: Function 'lib_mysqludf_sys_info' already exists
ERROR: unable to install the UDF
[root@hq-dv-mysql-101 lib_mysqludf_sys]#

**Comment by vivekgkp** [comment]
its fixed

**Comment by dmitryzykov** [comment]
@vivekgkp I have the same issue. How did you fix it?
